# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specgraph < Formula
  desc "Live spec-driven development framework"
  homepage "https://specgraph.io"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.5/specgraph_0.1.5_darwin_amd64.tar.gz"
      sha256 "d171ea9bd3d04d4eeea13749193f3d8f6197db7d170c29947253759ec43119a4"

      define_method(:install) do
        bin.install "specgraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.5/specgraph_0.1.5_darwin_arm64.tar.gz"
      sha256 "1ca9cae9dad1532c15c1ef5ad7bb0361a203873ab87d3a35da1f92b8f8fcb765"

      define_method(:install) do
        bin.install "specgraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.5/specgraph_0.1.5_linux_amd64.tar.gz"
      sha256 "c17be43cc815d6c321c36d6e0b861491397dfc64fa6dea5589fa993064347280"
      define_method(:install) do
        bin.install "specgraph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.5/specgraph_0.1.5_linux_arm64.tar.gz"
      sha256 "4391f62367cc32a9b97198806748f4fa79ec67c59443df0a28deb9e73b6ba3e5"
      define_method(:install) do
        bin.install "specgraph"
      end
    end
  end
end
