# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specgraph < Formula
  desc "Live spec-driven development framework"
  homepage "https://specgraph.io"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.6/specgraph_0.1.6_darwin_amd64.tar.gz"
      sha256 "d81fd61e4a1e186fff383917dedbd3219b8b205f0f62790ae442222daf29590e"

      define_method(:install) do
        bin.install "specgraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.6/specgraph_0.1.6_darwin_arm64.tar.gz"
      sha256 "84e5c6874485154db4f55ede99976621df3fc04791cbd0e960bce3c34e8b5f15"

      define_method(:install) do
        bin.install "specgraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.6/specgraph_0.1.6_linux_amd64.tar.gz"
      sha256 "a90a483d2a9c98495095aac54a8fa6abbf394fccfa1f216b90f13e4735e47854"
      define_method(:install) do
        bin.install "specgraph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/specgraph/specgraph/releases/download/v0.1.6/specgraph_0.1.6_linux_arm64.tar.gz"
      sha256 "b1224655a15d69a74cff47a9a16d40c156a016bcb4ecf3844bf59d00afa46d1d"
      define_method(:install) do
        bin.install "specgraph"
      end
    end
  end
end
