# This file was generated by GoReleaser. DO NOT EDIT.
cask "specgraph" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "9f8aa1597efe71a25db5b8b6b9396582b84c4aaec23b03aaa97bfe6b70335934"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63e37a51f726dd8197f25f7616f5ce4b236fe4702415b64a767feda4c9bfdd2f"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bdb07ca38e4c0dc5c4b82d9be0d555a5a343306fa2678ce69624b7d13ec4a156"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c1b6686c1818e466a3304ec0a398aede8b5b1121cd356c846cfa519e9b5614a"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "specgraph"
  desc "Live spec-driven development framework"
  homepage "https://specgraph.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specgraph"

  # No zap stanza required

end
