# This file was generated by GoReleaser. DO NOT EDIT.
cask "specgraph" do
  version "0.11.2"

  on_macos do
    on_intel do
      sha256 "b7c57f219d22034fcbccea1175f555db5b7bcb28c5b6c8b783f3b12c9169ebdb"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b71b0cd1e085835eaac8002a55cc3c2fa143d9bd7667c0e4a7a522498a69f8b3"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b61e1038f12264d1e93507fa3b2134d7be28df30cb515682cb998364073fc18"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4930974021285ff002c955c15cd2b143c849fc5c1eb8caf88300185de158773"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "specgraph"
  desc "Live spec-driven development framework"
  homepage "https://specgraph.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specgraph"

  # No zap stanza required

end
