# This file was generated by GoReleaser. DO NOT EDIT.
cask "specgraph" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "97b59b12a549b8cc9de78351f2c9fe7b4fb1c8de77a5a4bffa4baf75c648d542"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "215fde23e7c38f2183536315ca343e82d12644b11120ae7f425e8b6d9ab4bb52"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a481bd459430bb0318e3767b2913dcc0255e2f50f8e5ffbc57c5c4d31c669acc"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "34266c580705179e85829ee2e9d5ce32637c39e5ae79697f2351fb3200703a1d"
      url "https://github.com/specgraph/specgraph/releases/download/v#{version}/specgraph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "specgraph"
  desc "Live spec-driven development framework"
  homepage "https://specgraph.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specgraph"

  # No zap stanza required

end
